config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :tasks do
  collection do
    get 'search'
  end
end
  root 'tasks#index'
  get 'home/about'
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	def self.statuses
    {
      'completed' => 'Completed',
      'ongoing' => 'Ongoing',
      'pending' => 'Pending'
    }
  end
  validates :title, presence: true, on: :update
  validates :description, presence: true, on: :update
  validates :assigned_to, presence: true, on: :update
   validates :title, uniqueness: { message: " :The task with the same title already exists." }

  validates :title, :description, :duedate, :priority, :status, :category, :assigned_to, presence: true
  validate :assigned_to_must_not_contain_numbers
  validates :title, presence: true, length: { minimum: 5 } # Adjust the minimum length as needed
  validates :description, presence: true, length: { minimum: 10 }

  def assigned_to_must_not_contain_numbers
    if assigned_to.match?(/\d/)
      errors.add(:assignee, "cannot contain numbers")
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tasks or /tasks.json
  def index
    if user_signed_in?
      @tasks = current_user.tasks.paginate(page: params[:page], per_page: 10)
    else
    @tasks = Task.paginate(page: params[:page], per_page: 10)
  end
end

def search
    if params[:search].present?
      if user_signed_in?
         @tasks = current_user.tasks.where("title LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
      else
        @tasks = Task.where("title LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
      end
    else
      @tasks = user_signed_in? ? current_user.tasks.paginate(page: params[:page], per_page: 10) : Task.none.paginate(page: params[:page], per_page: 10)
    end

    render :index
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    #@task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    #@task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Not Authorized To Do This!" if @task.nil?
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:id, :title, :description, :duedate, :priority, :status, :category, :assigned_to, :created_at, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_footer.html.erb
<footer class="footer text-center" style="background-color: ; color:black;padding: 10px 0; font-family: Perpetua;" class="text-center">
  <div class="container">
     <p>&copy; <%= Time.now.year %> Mignonne Unguyeneza</p>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="font-family: inherit; font-size: 14px;">
  <%= link_to root_path, class: "navbar-brand" do %>
    ToDo App <i class="fas fa-check-circle"></i>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "User Guide", home_about_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Tasks", tasks_path, class:"nav-link"%>
      </li>

      
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Sign out",  destroy_user_session_path, method: :delete, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Add a Task", new_task_path, class:"nav-link"%>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
      </li>

      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
      </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0" action="<%= search_tasks_path %>" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="Search by title" aria-label="Search" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<div class="card">
  <h5 class="card-header">
    Welcome to the ToDo App User Guide
  </h5>
  <div class="card-body">
    <br/>
    <p>Thank you for choosing our ToDo App to help you manage your tasks and stay organized. This user guide will walk you through the various features and functionalities of our app, ensuring that you can make the most out of it.</p><br/>

    <h4 class="card-subtitle mb-2 text-muted">Table of Contents</h4><br/>
    <p><strong>Getting Started</strong></p>
    <ul>
      <li><strong>Creating an Account</strong></li>
      <p>To get started, create an account by clicking on the "Sign Up" link in the navigation menu. Provide your email and create a password. Once registered, you can log in to your account.</p>
      <li><strong>Logging In</strong></li>
      <p>Click on the "Sign In" link in the navigation menu to log in to your account. You'll be prompted to enter your email and password.</p>
      <li><strong>Remember Me Option</strong></li>
      <p>You can choose to enable the "Remember Me" option during login to stay logged in across sessions.</p>
    </ul>

    <p><strong>Dashboard</strong></p>
    <ul>
      <li><strong>Overview of the Task List</strong></li>
      <p>Upon logging in, you'll be directed to the dashboard, which displays your task list. You'll see a list of tasks that you've created, including their titles, due dates, priorities, and completion status.</p>
      <li><strong>View Options: List and Card Views</strong></li>
      <p>You can switch between list and card views for your tasks. The list view displays tasks in a tabular format, while the card view presents tasks as individual cards.</p>
      <li><strong>Search for Tasks</strong></li>
      <p>Use the search bar to find tasks quickly by typing keywords from the task title. The app will display matching tasks in real-time.</p>
    </ul>


    <p><strong>! Viewing Tasks for Different People and Searching</strong></p>
    <ul>
      <li>You have the ability to view all tasks for different people and search for a specific task even if you are not logged in. This feature allows you to browse through tasks created by various users and find the information you need.</strong></li></ul>

      <p><strong>! Authentication for Editing, Deleting, and Adding Tasks</strong></p>
    <ul>
      <li>However, please note that in order to edit, delete, and add tasks, you will need to log in to your account. This login requirement ensures that only authorized users can make changes to the tasks, maintaining the security and integrity of the task management process. Once you log in, you'll have full access to these functionalities and can efficiently manage your tasks within the app.</li></ul>
      <br/>

    <p><strong>Managing Tasks</strong></p>
    <ul>
      <li><strong>Creating New Tasks</strong></li>
      <p>To add a new task, click on "Add a Task" in the navigation menu. Fill in the required details such as title, description, due date, priority, and category.</p>
      <li><strong>Editing Existing Tasks</strong></li>
      <p>Click on a task to view its details. From here, you can edit any field, including title, description, due date, priority, and category.</p>
      <li><strong>Marking Tasks as Completed</strong></li>
      <p>When a task is completed, simply change the status to completed. The task will be marked as complete in green color.</p>
      <li><strong>Deleting Tasks</strong></li>
      <p>To remove a task, click on the task and then click delete button. Be cautious, as deleted tasks cannot be recovered.</p>
    </ul>

    <p><strong>Task Details</strong></p>
    <ul>
      <li><strong>Adding Notes and Descriptions</strong></li>
      <p>For each task, you can add additional notes or descriptions to provide more context or details.</p>
      <li><strong>Setting Due Dates and Priorities</strong></li>
      <p>Assign a due date to tasks to help you stay organized. You can also set task priorities to indicate their importance.</p>
      <li><strong>Categorizing Tasks</strong></li>
      <p>Categorize tasks into different categories, such as personal, work, or other custom categories.</p>
    </ul>

    <p><strong>User Profile</strong></p>
    <ul>
      <li><strong>Viewing and Editing Account Information</strong></li>
      <p>Access your user profile to view your account information. You can also edit your name and email address from here.</p>
      <li><strong>Changing Password</strong></li>
      <p>You can change your password by navigating to your profile and updating your password.</p>
    </ul>

    <p><strong>Responsive Design</strong></p>
    <ul>
      <li><strong>Accessing the App on Different Devices</strong></li>
      <p>The ToDo App is designed to be responsive, ensuring a seamless experience across devices like desktops, tablets, and mobile phones.</p>
    </ul>

    <p>We hope this user guide helps you navigate through the features and functionalities of our ToDo App.Happy task managing!</p>
  </div>
</div>

app/views/home/index.html.erb
<h1>My Todo App</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d92792f622.js" crossorigin="anonymous"></script>
    


    <title>Todo App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style type="text/css">
      /* In your CSS file */
.container-fluid {
  padding: 0; /* Remove padding */
  margin: 0; /* Remove margin */
}

    </style>
    
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container-fluid ">
      
      <% if notice %>
       <%= render 'layouts/alerts' %>
       <% end %>

    <%= yield %>
    <%= render "home/footer" %>
      
    </div>
   

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

 

  <div class="form-group" style="color:gray;">
    <%= form.label :DueDate %>
    <%= form.date_field :duedate, class: "form-control",min: Date.today %>
  </div>
   <div class="form-row">
    <div class="form-group col-md-4" style="color:gray;">
      <%= form.label :priority %>
      <%= form.select :priority, ['high', 'medium', 'low'], class: "form-control" %>
    </div>

    <div class="form-group col-md-4" style="color:gray;">
      <%= form.label :status %>
      <%= form.select :status, options_for_select(Task.statuses.keys, task.status), class: "form-control" %>
    </div>

    <div class="form-group col-md-4" style="color:gray;">
      <%= form.label :category %>
      <%= form.select :category, options_for_select(['work', 'business', 'personal', 'family', 'education']),class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.text_field :assigned_to, class: "form-control", placeholder: "Assigned To" %>
  </div>

  <div>
    <%= form.text_field :created_at, type: 'hidden' %>
  </div>


  <div class="form-group">
    <%= form.number_field :user_id, id: :task_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  

<br/>
  <div>
    <%= form.submit "Save Task", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% 
  def priority_highlight_class(priority)
    case priority
    when 'high'
      'bg-danger text-white'
    when 'medium'
      'bg-warning text-dark'
    when 'low'
      'bg-success text-white'
    else
      ''
    end
  end
%>

<% 
  def category_highlight_class(category)
    case category
    when 'work'
      'bg-primary text-white'
    when 'business'
      'bg-success text-white'
    when 'personal'
      'bg-info text-white'
    when 'family'
      'bg-warning text-dark'
    when 'education'
      'bg-danger text-white'
    else
      ''
    end
  end
%>

<% 
  def status_highlight_class(status)
    case status
    when 'completed'
      'bg-success text-white'
    when 'ongoing'
      'bg-primary text-white'
    when 'pending'
      'bg-warning text-dark'
    else
      ''
    end
  end
%>
<div id="<%= dom_id task %>">
  <tr  style="font-family:  Perpetua;">
    <td><%= task.id %></td>
    <td><%= link_to task.title, task %></td>
    <span class="description-toggle"><%= task.description %></span>
    <td><%= task.duedate %></td>
   <td>
      <% priority_class = priority_highlight_class(task.priority) %>
      <span class="rounded-pill px-2 py-1 <%= priority_class %>"><%= task.priority %></span>
    </td>
    
    
     <td>
      <% category_class = category_highlight_class(task.category) %>
      <span class="rounded-pill px-2 py-1 <%= category_class %>"><%= task.category %></span>
    </td>
    <td><%= task.assigned_to %></td>
    <td><%= task.created_at.strftime('%Y-%m-%d') %></td>
    <td>
      <% status_class = status_highlight_class(task.status) %>
      <span class="rounded-pill px-2 py-1 <%= status_class %>"><%= task.status %></span>
    </td>
   


    <td><%= link_to "Show", task, class: "btn btn-outline-secondary btn-sm" %></td>


  </tr>
</div>

app/views/tasks/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Modify task</h4>
  </div>
  <div class="card-body">
    <%= render "form", task: @task %>
    <%= link_to "Show this task", @task %> | 
  <%= link_to "Back to tasks", tasks_path %>
  </div>
</div>
  

app/views/tasks/index.html.erb
<style>
  .pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 20px;
  }

  .pagination a,
  .pagination span {
    display: inline-block;
    text-decoration: none;
    padding: 8px 16px;
    border: 1px solid #ccc;
    margin: 0 5px;
    color: #333;
  }

  .pagination a:hover,
  .pagination span:hover {
    background-color: #f2f2f2;
  }

  .pagination .current,
  .pagination .previous,
  .pagination .next {
    background-color: #f2f2f2;
    color: black;
    font-weight: bold;
    padding: 8px 16px;
    border: 1px solid #ccc;
  }
</style>






<div class="card" style="border-bottom: none;">
  <div class="card-header" >
    <b>TO DO LIST</b>
    <div id="tasks">
  <table class="table table-bordered table-hover" style="font-family: Perpetua;">
    <thead class=" " style="font-family:;">
      <tr>
        <th class="h6" style="border: none">#</th>
        <th class="h6" style="border: none">Title</th>
        <th class="h6" style="white-space: nowrap;border: none">Due Date</th>
        <th class="h6" style="border: none">Priority</th>
        <th class="h6" style="border: none">Category</th>
        <th class="h6" style="white-space: nowrap;border: none">Assigned to </th>
        <th class="h6" style="border: none">Sheduled on</th>
        <th class="h6" style="border: none">Status</th>
        <th class="h6" style="border: none"></th>
      </tr>
    </thead>
  </div>
  <div class="card-body">
    
    <tbody>
  <% @tasks.each do |task| %>
  <%= render partial: 'task', locals: { task: task } %>
  <% end %>
   </tbody>
  </table>
  <div class="pagination justify-content-center" >
    <%= will_paginate @tasks, renderer: WillPaginate::ActionView::LinkRenderer, class: 'pagination' %>
  </div>
  <%= link_to "Add a Task", new_task_path, class:"btn btn-secondary" %>

</div>

<%= javascript_tag do %>
  document.addEventListener("DOMContentLoaded", function() {
    const descriptionToggleElements = document.querySelectorAll(".description-toggle");
    const detailsLinks = document.querySelectorAll(".details-link");

    detailsLinks.forEach(link => {
      link.addEventListener("click", function(e) {
        e.preventDefault();
        const descriptionElement = this.closest("tr").querySelector(".description-toggle");
        descriptionElement.classList.toggle("show-description");
      });
    });
  });
<% end %>

<style>
  .description-toggle {
    display: none;
  }

  .show-description {
    display: table-cell;
  }
</style>


  </div>
</div>

app/views/tasks/new.html.erb
<div class="card">
  <div class="card-header">
     <h4>Add a Task</h4>
  </div>
  <div class="card-body">
    <%= render "form", task: @task %>
    <%= link_to "Back to tasks", tasks_path %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @task.title %></h1>
  <p class="lead"><%= @task.description %></p>
  <hr class="my-4">
  <p class="lead"><p>Due Date:</p><%= @task.duedate %> | <%= @task.status %></p>
  <div class="btn-group mt-2" role="group" aria-label="Button group">
    <%= link_to "Edit", edit_task_path(@task), class:"btn btn-secondary  rounded mr-1 px-3" %>
  <%= link_to "Back", tasks_path, class:"btn btn-info  rounded mr-1 px-3"%>
  <%= button_to "Delete", @task, method: :delete, class: "btn btn-danger  rounded mr-1 px-3" %>
    
  </div>
  
 
</div>